package com.example.mealy.database

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize

/**
 * Data class is just a fancy name for a simple class which contains some data members , and just methods for get and set of the variables
 * This is the Kotlin Version where we need only define the class Structure , the methods are generated by the compiler itself
 * For use in Java Code , for example in mealItem:
 * mealPlanObject.getMealItem() to get the string for mealItem
 *
 * Parcelize annotation instructs the compiler to autogenerate the required methods to make this class Parcelable using the Parcelable Interface
 */
@Entity(tableName = "meal_plan")
@Parcelize
data class MealPlan(
    @PrimaryKey(autoGenerate = true)
    val id: Int,
    val mealItem: String,
    val quantity: Int,
    val day: String,
    val type: String //BreakFast/Lunch/Dinner
) : Parcelable